name: cuzou_app
#name: Notee
description: Social Network for Shop.

#Add curved_navigation_bar: ^1.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#version principale 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
  #flutter: ">= 1.17.0"
  #Pour enlever le null safety, c'est sdk: ">=2.11.0 <3.0.0" OU "">=2.3.0 <3.0.0""
  #Ma version principale est >=2.15.1 <3.0.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #intl: ^0.15.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  flutter_zoom_drawer: any
  curved_navigation_bar: ^1.0.3
  date_format: ^2.0.5
  clickable_list_wheel_view: ^0.2.0
  intl: ^0.17.0
  flutter_rating_bar : ^4.0.0
  path_provider: ^2.0.10
  overlay_support: ^2.0.1
  image_picker: ^0.8.5+2
  #http: ^1.1.0
  #url_launcher: ^6.1.12

  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.4
  firebase_messaging: ^14.0.4
  http: ^0.13.5
  url_launcher: ^6.1.11
  permission_handler: ^10.4.3
  qr_code_scanner: ^1.0.1
  #firebase_auth: ^0.6.2+1
  #firebase_auth: ^3.3.17

  #list_wheel_scroll_view_x: ^0.0.2

  #Or flutter_zoom_drawer: ^2.0.0
  #Or flutter_zoom_drawer: ^2.1.1
  #flutter_icons: ^1.1.0
  #lite_rolling_switch: ^0.1.1
  
  
  #cloud_firestore: ^3.1.11
  #firebase_core: ^1.14.0

  #Recommended Version For FlutterFire
  #firebase_core: ^1.16.0
  #firebase_auth: ^3.3.17
  #firebase_storage: ^10.2.15
  #cloud_firestore: ^3.1.14

  #firebase_messaging: ^12.0.1


  #firebase_crashlytics: ^0.4.0
  #firebase_messaging: ^8.0.0-dev.15
  #firebase_storage: ^10.2.15

  #firebase_remote_config: "^0.8.0-dev.0"

dependency_overrides:
  #firebase_core_platform_interface: ^4.4.1
  #firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

  #integration_test:
  #  sdk: flutter
  #flutter_driver:
  #  sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/logo_notee/icon_noir_fond_blanc.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logos/logo_notee/icon_noir.png"
  # remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #Main images
    - assets/images/logos/waiting.png
    - assets/images/logos/logo_profile.png
    - assets/images/logos/photoPP.jpg
    - assets/images/logos/darkthemeexample.png
    - assets/images/logos/lightthemeexample.png
    - assets/images/logos/default_shop.png
    - assets/images/logos/logo_notee/logo_noir.png
    - assets/images/logos/logo_notee/logo_blanc.png
    - assets/images/logos/logo_notee/icon_noir_fond_blanc.png
    - assets/images/logos/logo_notee/icon_noir.png
    - assets/images/logos/logo_notee/icon_blanc.png
    - assets/images/logos/splash_anim_regular.gif
    - assets/images/logos/anim_fond_noir.gif
    - assets/images/logos/logo_notee/logo_gras_noir.png
    - assets/images/logos/logo_notee/logo_gras_blanc.png

    #Flags
    - assets/images/logos/flags/english_flag.png
    - assets/images/logos/flags/french_flag.png

    #Image example for shops
    - assets/images/image_shop/boulangerie1.jpg
    - assets/images/image_shop/boulangerie2.jpg
    - assets/images/image_shop/boucherie1.jpg
    - assets/images/image_shop/hotel1.jpg
    - assets/images/image_shop/hotel2.jpg
    - assets/images/image_shop/hotel3.jpg

    #Image example for news
    - assets/images/image_news/pain_news.jpg
    - assets/images/image_news/service_chambre_news.jpg
    - assets/images/image_news/spa.jpg
    - assets/images/image_news/spa_construction.jpg

    #Categorie logos
    - assets/images/logos/category_logos/logo_bar.png
    - assets/images/logos/category_logos/logo_hotel.png
    - assets/images/logos/category_logos/logo_restaurant.png
    - assets/images/logos/category_logos/logo_epicerie_fine.png
    - assets/images/logos/category_logos/logo_service.png
    - assets/images/logos/category_logos/logo_mode.png

    #SubCategorie Logos
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_1.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_2.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_3.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_4.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_5.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_6.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_7.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_8.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_9.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_10.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_11.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_12.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_13.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_15.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_16.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_17.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_18.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_19.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_20.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_21.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_22.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_23.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_24.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_25.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_26.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_27.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_28.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_29.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_30.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_31.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_32.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_33.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_34.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_35.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_36.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_37.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_38.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_39.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_40.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_41.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_42.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_43.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_44.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_45.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_46.png
    - assets/images/logos/subcategory_logos/Pictogrammes_Sous-categories_47.png

    #Navigation Bar Logo
    - assets/images/logos/navigation_bar_logo/home.png
    - assets/images/logos/navigation_bar_logo/journal.png
    - assets/images/logos/navigation_bar_logo/lettre.png

    #Visibility logo
    - assets/images/logos/visibility_logos/diamond.png
    - assets/images/logos/visibility_logos/gold.png
    - assets/images/logos/visibility_logos/silver.png
    - assets/images/logos/visibility_logos/bronze.png

    #Profil Picture - Notee team
    - assets/images/notee_team/Jonathan.jpg
    - assets/images/notee_team/alexandre.jpeg
    - assets/images/notee_team/cynthia.jpg
    - assets/images/notee_team/mael.jpg



  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

    - family: RebondGrotesque
      fonts: 
        - asset: assets/fonts/Notee_Typo/RebondGrotesque-Regular.otf
        - asset: assets/fonts/Notee_Typo/RebondGrotesque-Bold.otf
          weight: 700
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-BoldItalic.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Extrabold.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-ExtraboldItalic.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Extralight.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-ExtralightItalic.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Hairline.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-HairlineItalic.otf
        - asset: assets/fonts/Notee_Typo/RebondGrotesque-Light.otf
          weight: 300
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-LightItalic.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Medium.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-MediumItalic.otf
        - asset: assets/fonts/Notee_Typo/RebondGrotesque-RegularItalic.otf
          style: italic
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Semibold.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-SemiboldItalic.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-Thin.otf
        #- asset: assets/fonts/Notee_Typo/RebondGrotesque-ThinItalic.otf
          
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
